-- MySQL Script generated by MySQL Workbench
-- Sat Aug  8 07:29:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE centroautomotriz;
USE centroautomotriz;

CREATE TABLE IF NOT EXISTS `departamentos` (
  `id_depto` INT NOT NULL AUTO_INCREMENT,
  `nom_depto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_depto`)
);

CREATE TABLE IF NOT EXISTS `ciudades` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nom_ciudad` VARCHAR(50) NOT NULL,
  `id_depto` INT NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  INDEX `fk_ciudades_departamentos_idx` (`id_depto` ASC) ,
  CONSTRAINT `fk_ciudades_departamentos`
    FOREIGN KEY (`id_depto`)
    REFERENCES `departamentos` (`id_depto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE `sucursales` (
  `id_sucursal` int(11) NOT NULL AUTO_INCREMENT,
  `nom_sucursal` varchar(80) NOT NULL,
  `dir_sucursal` varchar(100) NOT NULL,
  `tel_sucursal` decimal(10,0) DEFAULT NULL,
  `id_ciudad` int(11) NOT NULL,
  PRIMARY KEY (`id_sucursal`),
  CONSTRAINT `fk_ciudades1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `ciudades` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `servicios` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nom_servicio` VARCHAR(30) NOT NULL,
  `valor_servicio` DECIMAL(7,0) NOT NULL,
  `tiempo_servicio` DECIMAL(5,1) NOT NULL,
  `id_sucursal` INT NOT NULL,
  PRIMARY KEY (`id_servicio`),
  CONSTRAINT `fk_servicios_areas1`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `sucursales` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE `clientes` (
  `nro_doc_cliente` DECIMAL(10,0) NOT NULL,
  `contrasena` VARCHAR(128) NOT NULL,
  `nom_cliente` VARCHAR(50) NOT NULL,
  `ape_cliente` VARCHAR(50) NOT NULL,
  `correo_cliente` VARCHAR(100) NOT NULL,
  `tel_cliente` DECIMAL(10,0) NULL,
  PRIMARY KEY (`nro_doc_cliente`)
);

CREATE TABLE IF NOT EXISTS `estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(15) NOT NULL,
   PRIMARY KEY (`id_estado`)
);

CREATE TABLE IF NOT EXISTS `horarios` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `horario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_horario`)
);

CREATE TABLE IF NOT EXISTS `turnos` (
  `id_turno` INT NOT NULL AUTO_INCREMENT,
  `fecha_turno` DATE NOT NULL,
  `horario` INT NOT NULL,
  `estado_turno` INT NOT NULL,
  `obs_turno` VARCHAR(250) NULL,
  `cod_reserva` VARCHAR(6) NULL,
  `id_servicio` INT NOT NULL,
  `nro_doc_cliente` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id_turno`),
  CONSTRAINT `fk_turnos_servicios1`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turnos_estado1`
    FOREIGN KEY (`estado_turno`)
    REFERENCES `estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turnos_clientes1`
    FOREIGN KEY (`nro_doc_cliente`)
    REFERENCES `clientes` (`nro_doc_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turnos_horarios1`
    FOREIGN KEY (`horario`)
    REFERENCES `horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


